baseURL = "https://l2n.me"
title = "luanguimaraesla"
theme = "vec"
languageCode = "en-us"
paginate = 15

publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

[menu]
  [[menu.main]]
    name = "about"
    weight = 100
    url = "/about"
  [[menu.main]]
    name = "presentations"
    weight = 0
    url = "https://slides.l2n.me"
  [[menu.main]]
    name = "astronomy"
    weight = 0
    url = "https://astro.l2n.me"

[params]
  Keywords = "luan, climb, developer, sail, bike, music, code"
  Description = "personal page"
  
  Avatar = "img/me.jpg"
  SelfIntro = "learning to be human" 
  Email = "luang@riseup.net"
  
  GithubID = "luanguimaraesla"
  TwitterID = "luanguimaraesla"
  LinkedInID = "luanguimaraesla"
